### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module

### ISSUE THREAD

**Issue by kwiniarski** [andrewcourtice/harlem#32]
**Describe the bug**
I have a simple template of Vue application build with Vite. After update to Harlem 2.0.0-beta.0 I have following error:

```
20:14:50 [vite] Error when evaluating SSR module /src/entry-server.ts:
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Projects\vite-template\node_modules\.pnpm\@harlem+utilities@2.0.0-beta.0\node_modules\@harlem\utilities\dist\index.js
require() of ES modules is not supported.
require() of C:\Projects\vite-template\node_modules\.pnpm\@harlem+utilities@2.0.0-beta.0\node_modules\@harlem\utilities\dist\index.js from C:\Projects\vite-template\node_modules\.pnpm\@harlem+core@2.0.0-beta.0_vue@3.2.2\node_modules\@harlem\core\dist\index.cjs is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Projects\vite-template\node_modules\.pnpm\@harlem+utilities@2.0.0-beta.0\node_modules\@harlem\utilities\package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at n (C:\Projects\vite-template\node_modules\.pnpm\jiti@1.11.0\node_modules\jiti\dist\v8cache.js:2:2472)
    at Object.<anonymous> (C:\Projects\vite-template\node_modules\.pnpm\@harlem+core@2.0.0-beta.0_vue@3.2.2\node_modules\@harlem\core\dist\index.cjs:80:18)
    at Module.o._compile (C:\Projects\vite-template\node_modules\.pnpm\jiti@1.11.0\node_modules\jiti\dist\v8cache.js:2:2778)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
```

**Expected behaviour**
Application should work correctly. Version 1.3.2 seems to work as expected.

**Version (please complete the following information):**
 - Harlem: 2.0.0-beta.0
 - Vue: 3.2.2
 - Vite: 2.5.0
 - Runtime Environment: Node.js 14.15.4

**Comment by andrewcourtice** [comment]
@kwiniarski thanks for raising this. I've likely misconfigured the package.json. I'll fix it up and release a new beta version.

**Comment by andrewcourtice** [comment]
@kwiniarski Try the beta 1 release and let me know how you go

**Comment by kwiniarski** [comment]
@andrewcourtice Seems that beta 1 solves the problem. Thank you.
