### ISSUE TITLE
Using Vue + Vite + Harlem with SSR

### ISSUE THREAD

**Issue by lermontex** [andrewcourtice/harlem#75]
**Describe the bug**
I have a completed application. I am using Vue 3 + Vite + Harlem. Now I'm trying to set up SSR, but an error occurs.

```
$ node --trace-warnings ./server.js
http://localhost:3000
TypeError: Cannot read properties of undefined (reading 'createVuePlugin') 
    at /src/store/index.js:5:14
    at async instantiateModule (file:///C:/Projects/website/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:52224:9)
```

```
$ cross-env NODE_ENV=production node --trace-warnings ./server.js
http://localhost:3000 
ReferenceError: window is not defined 
    at file:///C:/Projects/website/node_modules/@harlem/core/dist/index.bundler.mjs:481:1
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

// store/index.js
```
import { createVuePlugin } from "@harlem/core";
import { createServerSSRPlugin } from "@harlem/plugin-ssr";
import storageExtension from "@harlem/extension-storage";

const store = createVuePlugin({
  plugins: [createServerSSRPlugin()],
});

export const storageExt = storageExtension({
  type: "local",
  prefix: "app",
  sync: true,
});

export default store;
```

**Version (please complete the following information):**
 - Harlem: 3.0.2
 - Vue: 3.2.38
 - Vite: 4.0.4
 - Express: 4.18.2
 - Node JS: 18.13.0

**Comment by andrewcourtice** [comment]
Hi @lermontex - thanks for picking up on this one. A fix is on it's way in the next release 👍
